package com.analyzer.engine;

import burp.api.montoya.MontoyaApi;
import burp.api.montoya.http.message.requests.HttpRequest;
import burp.api.montoya.http.message.responses.HttpResponse;
import com.analyzer.checks.Check;
import com.analyzer.checks.active.CorsCheck;
import com.analyzer.checks.active.HostHeaderCheck;
import com.analyzer.checks.active.HttpMethodsCheck;
import com.analyzer.checks.active.SensitivePathsCheck;
import com.analyzer.checks.passive.CookieFlagsCheck;
import com.analyzer.checks.passive.FormSecurityCheck;
import com.analyzer.checks.passive.HtmlCommentsCheck;
import com.analyzer.checks.passive.InfoDisclosureCheck;
import com.analyzer.checks.passive.JavaScriptGrepCheck;
import com.analyzer.checks.passive.RobotsSitemapCheck;
import com.analyzer.checks.passive.SecurityHeadersCheck;
import com.analyzer.checks.passive.TechFingerprintCheck;
import com.analyzer.checks.tls.TlsCheck;
import com.analyzer.model.Finding;
import com.analyzer.traffic.HttpTrafficLog;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Consumer;

/**
 * Coordinates a single analysis run: dispatches every registered Check on a worker pool and
 * streams findings back through the supplied callback so the UI can update incrementally.
 * All HTTP traffic generated by checks is captured in the shared HttpTrafficLog.
 */
public final class AnalysisEngine {
    private final MontoyaApi api;
    private final HttpTrafficLog trafficLog;
    private final List<Check> checks;

    public AnalysisEngine(MontoyaApi api, HttpTrafficLog trafficLog) {
        this.api = api;
        this.trafficLog = trafficLog;
        this.checks = defaultChecks();
    }

    private static List<Check> defaultChecks() {
        List<Check> list = new ArrayList<>();
        // Passive — read-only of the seed response (TechFingerprintCheck is borderline; it may fetch /)
        list.add(new TechFingerprintCheck());
        list.add(new SecurityHeadersCheck());
        list.add(new CookieFlagsCheck());
        list.add(new InfoDisclosureCheck());
        list.add(new HtmlCommentsCheck());
        list.add(new FormSecurityCheck());
        list.add(new RobotsSitemapCheck());
        list.add(new JavaScriptGrepCheck());
        // Active — additional traffic
        list.add(new HostHeaderCheck());
        list.add(new CorsCheck());
        list.add(new HttpMethodsCheck());
        list.add(new SensitivePathsCheck());
        // TLS — connects directly to host:443 with the local JDK
        list.add(new TlsCheck());
        return list;
    }

    public List<Check> checks() { return List.copyOf(checks); }

    /**
     * Run all checks against the given seed request. The onFinding callback may be invoked from
     * worker threads; the onComplete callback fires once after every check has finished.
     */
    /** Per-check hard timeout. A single slow check should never stall the whole run. */
    private static final long PER_CHECK_TIMEOUT_SECONDS = 60;
    /** Overall hard ceiling — `shutdownNow` after this. Stragglers get logged but the run completes. */
    private static final long OVERALL_TIMEOUT_SECONDS   = 180;

    public void analyze(HttpRequest seedRequest,
                        HttpResponse seedResponse,
                        Consumer<Finding> onFinding,
                        Runnable onComplete) {
        ExecutorService pool = Executors.newFixedThreadPool(
                Math.min(8, Math.max(2, checks.size())),
                namedDaemonThreadFactory("analyze-target-worker"));

        // After onComplete fires, slow stragglers may still emit findings — gate them out
        // so they don't land in a UI table the user just cleared.
        AtomicBoolean done = new AtomicBoolean(false);

        List<CompletableFuture<Void>> futures = new ArrayList<>();
        try {
            for (Check check : checks) {
                AnalysisContext ctx = new AnalysisContext(api, seedRequest, seedResponse, check.id(), trafficLog);
                CompletableFuture<Void> f = CompletableFuture.runAsync(() -> {
                    try {
                        api.logging().logToOutput("[analyze-target] running check: " + check.id());
                        List<Finding> found = check.run(ctx);
                        if (found != null && !done.get()) {
                            for (Finding x : found) {
                                if (x != null && !done.get()) onFinding.accept(x);
                            }
                        }
                    } catch (Exception e) {
                        api.logging().logToError("[analyze-target] check " + check.id() + " threw: " + e);
                    }
                }, pool).orTimeout(PER_CHECK_TIMEOUT_SECONDS, TimeUnit.SECONDS)
                        .exceptionally(ex -> {
                            if (ex instanceof TimeoutException
                                    || (ex.getCause() != null && ex.getCause() instanceof TimeoutException)) {
                                api.logging().logToError("[analyze-target] check " + check.id()
                                        + " exceeded " + PER_CHECK_TIMEOUT_SECONDS + "s timeout");
                            }
                            return null;
                        });
                futures.add(f);
            }
        } catch (Throwable submissionFailure) {
            api.logging().logToError("[analyze-target] submission failed: " + submissionFailure);
            shutdownPool(pool);
            if (onComplete != null) onComplete.run();
            return;
        }

        CompletableFuture
                .allOf(futures.toArray(new CompletableFuture[0]))
                .orTimeout(OVERALL_TIMEOUT_SECONDS, TimeUnit.SECONDS)
                .whenComplete((v, t) -> {
                    done.set(true);
                    if (t != null) {
                        api.logging().logToError("[analyze-target] overall run did not finish cleanly: " + t);
                    }
                    try {
                        if (onComplete != null) onComplete.run();
                    } finally {
                        shutdownPool(pool);
                    }
                });
    }

    private static void shutdownPool(ExecutorService pool) {
        pool.shutdown();
        try {
            if (!pool.awaitTermination(2, TimeUnit.SECONDS)) {
                pool.shutdownNow();
            }
        } catch (InterruptedException e) {
            pool.shutdownNow();
            Thread.currentThread().interrupt();
        }
    }

    private static ThreadFactory namedDaemonThreadFactory(String prefix) {
        AtomicInteger counter = new AtomicInteger();
        return r -> {
            Thread t = new Thread(r, prefix + "-" + counter.incrementAndGet());
            t.setDaemon(true);
            return t;
        };
    }
}
