package com.analyzer.report;

import com.analyzer.model.Finding;
import com.analyzer.model.Severity;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders a list of findings as a single self-contained HTML file (inlined CSS, no external links).
 * Findings are grouped by URL, then sorted by severity within each group.
 */
public final class HtmlReportWriter {
    private HtmlReportWriter() {}

    public static String render(List<Finding> findings) {
        EnumMap<Severity, Integer> counts = new EnumMap<>(Severity.class);
        for (Severity s : Severity.values()) counts.put(s, 0);
        for (Finding f : findings) counts.merge(f.severity(), 1, Integer::sum);

        // Group by URL, preserve insertion order
        Map<String, java.util.List<Finding>> byUrl = new LinkedHashMap<>();
        for (Finding f : findings) {
            byUrl.computeIfAbsent(f.url(), k -> new java.util.ArrayList<>()).add(f);
        }
        for (List<Finding> list : byUrl.values()) {
            list.sort(Comparator.comparingInt((Finding x) -> x.severity().ordinal())
                    .thenComparing(Finding::title));
        }

        StringBuilder sb = new StringBuilder(64 * 1024);
        sb.append("<!doctype html><html lang='en'><head><meta charset='utf-8'>")
          .append("<title>Analyze Target Report</title>")
          .append("<style>").append(css()).append("</style></head><body>");

        sb.append("<header><h1>Analyze Target - Reconnaissance Report</h1>")
          .append("<p class='gen'>Generated ")
          .append(escape(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
                  .format(ZonedDateTime.now(ZoneId.systemDefault()))))
          .append("</p></header>");

        // Summary
        sb.append("<section class='summary'><h2>Summary</h2><table class='counts'><tr>");
        for (Severity s : Severity.values()) {
            sb.append("<th class='sev-").append(s.name().toLowerCase()).append("'>")
              .append(s.label()).append("</th>");
        }
        sb.append("</tr><tr>");
        for (Severity s : Severity.values()) {
            sb.append("<td>").append(counts.get(s)).append("</td>");
        }
        sb.append("</tr></table>");
        sb.append("<p><strong>Total findings:</strong> ").append(findings.size())
          .append(" across <strong>").append(byUrl.size()).append("</strong> URL(s).</p></section>");

        // TOC
        sb.append("<section class='toc'><h2>Targets</h2><ul>");
        int idx = 0;
        for (String url : byUrl.keySet()) {
            sb.append("<li><a href='#t").append(idx++).append("'>")
              .append(escape(url)).append("</a> - ")
              .append(byUrl.get(url).size()).append(" finding(s)</li>");
        }
        sb.append("</ul></section>");

        // Per-URL sections
        idx = 0;
        for (Map.Entry<String, List<Finding>> e : byUrl.entrySet()) {
            sb.append("<section class='target' id='t").append(idx++).append("'>");
            sb.append("<h2>").append(escape(e.getKey())).append("</h2>");
            for (Finding f : e.getValue()) {
                renderFinding(sb, f);
            }
            sb.append("</section>");
        }

        sb.append("<footer><p>Generated by the Analyze Target Burp extension.</p></footer>");
        sb.append("</body></html>");
        return sb.toString();
    }

    private static void renderFinding(StringBuilder sb, Finding f) {
        sb.append("<article class='finding sev-").append(f.severity().name().toLowerCase()).append("'>");
        sb.append("<header><span class='sev-tag sev-").append(f.severity().name().toLowerCase())
          .append("'>").append(f.severity().label()).append("</span>");
        sb.append(" <span class='conf-tag'>").append(f.confidence().label()).append("</span>");
        sb.append(" <code>").append(escape(f.checkId())).append("</code>");
        sb.append("<h3>").append(escape(f.title())).append("</h3></header>");

        if (!f.description().isEmpty()) {
            sb.append("<h4>Description</h4><p>").append(escape(f.description())).append("</p>");
        }
        if (!f.remediation().isEmpty()) {
            sb.append("<h4>Remediation</h4><p>").append(escape(f.remediation())).append("</p>");
        }
        if (!f.evidence().isEmpty()) {
            sb.append("<h4>Evidence</h4><pre>").append(escape(f.evidence())).append("</pre>");
        }
        if (!f.requestSnippet().isEmpty() || !f.responseSnippet().isEmpty()) {
            sb.append("<details><summary>Request / response</summary>");
            if (!f.requestSnippet().isEmpty()) {
                sb.append("<h4>Request</h4><pre>").append(escape(f.requestSnippet())).append("</pre>");
            }
            if (!f.responseSnippet().isEmpty()) {
                sb.append("<h4>Response</h4><pre>").append(escape(f.responseSnippet())).append("</pre>");
            }
            sb.append("</details>");
        }
        if (!f.references().isEmpty()) {
            sb.append("<h4>References</h4><ul>");
            for (String r : f.references()) {
                String safeHref = safeHttpUrl(r);
                if (safeHref != null) {
                    sb.append("<li><a href='").append(escape(safeHref))
                      .append("' rel='noopener' target='_blank'>")
                      .append(escape(r)).append("</a></li>");
                } else {
                    // Don't render as a link if the scheme isn't http(s) - could be javascript: / data:
                    sb.append("<li>").append(escape(r)).append("</li>");
                }
            }
            sb.append("</ul>");
        }
        sb.append("</article>");
    }

    /** Returns the URL only if it parses to an http(s) scheme; otherwise null (so callers can refuse to render a link). */
    private static String safeHttpUrl(String url) {
        if (url == null) return null;
        String trimmed = url.trim();
        try {
            java.net.URI u = java.net.URI.create(trimmed);
            String scheme = u.getScheme();
            if (scheme != null && (scheme.equalsIgnoreCase("http") || scheme.equalsIgnoreCase("https"))) {
                return trimmed;
            }
        } catch (IllegalArgumentException ignored) {
        }
        return null;
    }

    private static String escape(String s) {
        if (s == null) return "";
        StringBuilder b = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '&' -> b.append("&amp;");
                case '<' -> b.append("&lt;");
                case '>' -> b.append("&gt;");
                case '"' -> b.append("&quot;");
                case '\'' -> b.append("&#39;");
                default -> b.append(c);
            }
        }
        return b.toString();
    }

    private static String css() {
        return """
            :root {
              --bg: #fafafa; --fg: #1f2933; --muted: #52606d; --card: #fff; --border: #d9e2ec;
              --critical: #b71c1c; --critical-bg: #ffebee;
              --high: #e65100;    --high-bg: #fff3e0;
              --medium: #f9a825;  --medium-bg: #fffde7;
              --low: #2e7d32;     --low-bg: #e8f5e9;
              --info: #1565c0;    --info-bg: #e3f2fd;
            }
            body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                   color: var(--fg); background: var(--bg); margin: 0; padding: 24px; max-width: 1100px; margin: 0 auto; }
            header h1 { margin: 0 0 4px; }
            .gen { color: var(--muted); margin-top: 0; }
            section { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
                      padding: 20px; margin: 20px 0; }
            section.summary table.counts { border-collapse: collapse; }
            section.summary th, section.summary td { padding: 6px 12px; text-align: center; border: 1px solid var(--border); font-weight: 500; }
            .toc ul { list-style: none; padding-left: 0; }
            .toc li { padding: 2px 0; }
            article.finding { border-left: 4px solid var(--border); padding: 8px 16px; margin: 16px 0;
                              background: var(--card); border-radius: 0 6px 6px 0; }
            article.finding header { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }
            article.finding h3 { width: 100%; margin: 4px 0 8px; }
            article.finding h4 { margin: 12px 0 4px; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
            article.finding pre { background: #f1f4f8; padding: 10px; border-radius: 4px; overflow-x: auto;
                                  font: 12px/1.5 ui-monospace, SFMono-Regular, Menlo, monospace; max-height: 300px; }
            article.finding details { margin-top: 8px; }
            article.finding details summary { cursor: pointer; color: var(--muted); }
            .sev-tag { padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: uppercase; }
            .conf-tag { padding: 2px 8px; border-radius: 12px; font-size: 11px; background: #eef2f7; color: var(--muted); }
            .sev-critical { background: var(--critical-bg); color: var(--critical); border-left-color: var(--critical) !important; }
            .sev-high     { background: var(--high-bg);     color: var(--high);     border-left-color: var(--high) !important; }
            .sev-medium   { background: var(--medium-bg);   color: var(--medium);   border-left-color: var(--medium) !important; }
            .sev-low      { background: var(--low-bg);      color: var(--low);      border-left-color: var(--low) !important; }
            .sev-info     { background: var(--info-bg);     color: var(--info);     border-left-color: var(--info) !important; }
            footer { color: var(--muted); text-align: center; margin: 32px 0; font-size: 12px; }
            code { font: 12px ui-monospace, SFMono-Regular, Menlo, monospace; background: #eef2f7; padding: 1px 4px; border-radius: 3px; }
            """;
    }
}
